version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: config/app/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    volumes:
      - ./media:/code/media
      - ./static:/code/static

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  celery:
    build:
      context: .
      dockerfile: config/celery/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env

    restart: always


  nginx:
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    volumes:
      - ./media:/code/media
      - ./static:/code/static
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

