# Generated by Django 5.2.4 on 2025-07-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/bg/%Y/%m/%d/')),
                ('background_type', models.CharField(choices=[('background_photo', 'Фото на фон'), ('just_photo', 'Просто фото')], default='background_photo', max_length=20)),
            ],
            options={
                'db_table': 'background_banner',
            },
        ),
        migrations.CreateModel(
            name='CardCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('term', models.TextField()),
                ('logo_image', models.ImageField(upload_to='cinemas/logos/%Y/%m/%d/')),
                ('top_banner', models.ImageField(upload_to='cinemas/banners/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'card_cinema',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('published_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(upload_to='movies/main/%Y/%m/%d/')),
                ('url', models.URLField()),
                ('is_2d', models.BooleanField(default=False)),
                ('is_3d', models.BooleanField(default=True)),
                ('is_imax', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_speed', models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')], default=5)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'news_banner',
            },
        ),
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('keywords_uk', models.CharField(max_length=255, null=True)),
                ('keywords_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'db_table': 'seo_metadata',
            },
        ),
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_speed', models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')], default=5)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'top_banner',
            },
        ),
        migrations.CreateModel(
            name='CardHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema_image', models.ImageField(blank=True, null=True, upload_to='halls/schema/%Y/%m/%d/')),
                ('top_banner', models.ImageField(blank=True, null=True, upload_to='halls/banners/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.cardcinema')),
            ],
            options={
                'db_table': 'card_hall',
            },
        ),
        migrations.CreateModel(
            name='FiledValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('movie', 'Movie'), ('card_cinema', 'Card Cinema'), ('card_hall', 'Card Hall'), ('seo_metadata', 'Seo Metadata'), ('main_page', 'Main Page'), ('publication', 'Publication'), ('news', 'Новини'), ('shares', 'Акції'), ('about', 'Про нас'), ('cafe_bar', 'Кафе/Бар'), ('vip_hall', 'VIP-зал'), ('advertising', 'Реклама'), ('children_room', 'Дитяча кімната')])),
                ('field_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('ru', 'Russian'), ('uk', 'Ukrainian')])),
                ('value', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'filed_value_translation',
                'unique_together': {('model_name', 'field_name', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='CardHallGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.cardhall')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.images')),
            ],
            options={
                'db_table': 'card_hall_gallery',
            },
        ),
        migrations.AddField(
            model_name='cardhall',
            name='gallery',
            field=models.ManyToManyField(related_name='hall_galleries', through='adminlte.CardHallGallery', to='adminlte.images'),
        ),
        migrations.CreateModel(
            name='CardCinemaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.cardcinema')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.images')),
            ],
            options={
                'db_table': 'card_cinema_gallery',
            },
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='gallery',
            field=models.ManyToManyField(related_name='cinema_galleries', through='adminlte.CardCinemaGallery', to='adminlte.images'),
        ),
        migrations.CreateModel(
            name='MovieGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.images')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.movie')),
            ],
            options={
                'db_table': 'movie_gallery',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='gallery',
            field=models.ManyToManyField(related_name='movie_galleries', through='adminlte.MovieGallery', to='adminlte.images'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('published_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('main_image', models.ImageField(upload_to='publications/%Y/%m/%d/')),
                ('video_url', models.URLField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('publication_type', models.CharField(choices=[('news', 'Новости'), ('shares', 'Акции'), ('about', 'Про нас'), ('cafe_bar', 'Кафе/Бар'), ('vip_hall', 'VIP-зал'), ('advertising', 'Реклама'), ('children_room', 'Дитяча кімната')], max_length=20)),
                ('gallery', models.ManyToManyField(to='adminlte.images')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='adminlte.seometadata')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_seo', to='adminlte.seometadata'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('phone_1', models.CharField(max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50, null=True)),
                ('seo_text', models.TextField(blank=True)),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_page', to='adminlte.seometadata')),
            ],
            options={
                'db_table': 'main_page',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, upload_to='contacts/%Y/%m/%d/')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='adminlte.seometadata')),
            ],
            options={
                'db_table': 'contacts_page',
            },
        ),
        migrations.AddField(
            model_name='cardhall',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_hall', to='adminlte.seometadata'),
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='seo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_cinema', to='adminlte.seometadata'),
        ),
        migrations.CreateModel(
            name='TopBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=255)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminlte.topbanner')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.images')),
            ],
            options={
                'db_table': 'top_banner_images',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('password_hash', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=32)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('uk', 'Ukrainian')], max_length=2)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('w', 'Women')], max_length=1)),
                ('birthday', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.city')),
            ],
        ),
        migrations.CreateModel(
            name='NewsBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=255)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='adminlte.newsbanner')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlte.images')),
            ],
            options={
                'db_table': 'news_banner_images',
                'unique_together': {('banner', 'image')},
            },
        ),
    ]
