# Generated by Django 5.2.3 on 2025-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiledLabelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('movie', 'Movie'), ('card_cinema', 'Card Cinema'), ('card_hall', 'Card Hall'), ('seo_metadata', 'Seo Metadata'), ('main_page', 'Main Page'), ('publication', 'Publication'), ('news', 'Новини'), ('shares', 'Акції'), ('about', 'Про нас'), ('cafe_bar', 'Кафе/Бар'), ('vip_hall', 'VIP-зал'), ('advertising', 'Реклама'), ('children_room', 'Дитяча кімната')])),
                ('field_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('ru', 'Russian'), ('uk', 'Ukrainian')])),
                ('label', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'filed_label_translation',
                'unique_together': {('model_name', 'field_name', 'language_code')},
            },
        ),
    ]
