# Generated by Django 5.2.3 on 2025-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbannerimage',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topbannerimage',
            name='url',
            field=models.URLField(),
        ),
    ]
