# Generated by Django 5.2.4 on 2025-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_image',
            field=models.ImageField(upload_to='movies/main/%Y/%m/%d/'),
        ),
    ]
