# Generated by Django 5.2.4 on 2025-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatesMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='templates/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'templates_mailing',
            },
        ),
    ]
