# Generated by Django 5.2.4 on 2025-07-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcinema',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='term_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cardcinema',
            name='term_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cardhall',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardhall',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardhall',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardhall',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
