# Generated by Django 5.2.4 on 2025-07-21 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
