# Generated by Django 5.2.4 on 2025-07-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0002_cardcinema_description_ru_cardcinema_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhall',
            name='schema_image',
            field=models.ImageField(upload_to='halls/schema/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cardhall',
            name='top_banner',
            field=models.ImageField(upload_to='halls/banners/%Y/%m/%d/'),
        ),
    ]
