# Generated by Django 5.2.3 on 2025-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0002_filedlabeltranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('news', 'Новини'), ('shares', 'Акції'), ('about', 'Про нас'), ('cafe_bar', 'Кафе/Бар'), ('vip_hall', 'VIP-зал'), ('advertising', 'Реклама'), ('children_room', 'Дитяча кімната')], max_length=20, null=True),
        ),
    ]
