# Generated by Django 5.2.3 on 2025-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0003_alter_publication_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometadata',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
